server:
  port: 8089
  address: 0.0.0.0

# cassandra:
#   enabled: true
#   embedded: true
# #   host: ${services.cassandra.host:localhost}

spinnaker:
  baseUrl: http://localhost:9000
  cassandra:
    enabled: false

  inMemory:
    enabled: true



front50:
  baseUrl: http://front50:8080

orca:
  baseUrl: http://orca:8083

endpoints.health.sensitive: false

slack:
  enabled: false

# spring:
#   mail:
#     host: ${mail.host}

mail:
  enabled: false
  host: ${services.echo.notifications.mail.host}
  from: ${services.echo.notifications.mail.fromAddress}

hipchat:
  enabled: false
  baseUrl: ${services.echo.notifications.hipchat.url}
  token: ${services.echo.notifications.hipchat.token}

twilio:
  enabled: false
  baseUrl: ${services.echo.notifications.sms.url:https://api.twilio.com/}
  account: ${services.echo.notifications.sms.account}
  token: ${services.echo.notifications.sms.token}
  from: ${services.echo.notifications.sms.from}

scheduler:
  compensationJob:
    enabled: true
    windowMs: 1800000 # optional

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false
    prototypeFilter:
      path: ${services.spectator.webEndpoint.prototypeFilter.path:}

  stackdriver:
    enabled: false
    projectName: ${services.stackdriver.projectName}
    credentialsPath: ${services.stackdriver.credentialsPath}