server:
  port: 8080
  address: 0.0.0.0
redis:
  enabled: true
  connection: redis://redis:6379
  host: redis
  port: 6379
  scheduler: default
  parallelism: -1
  secure: false


cassandra:
  enabled: false

spinnaker:

  redis:
    enabled: true
    secure: false
    connection: redis://redis:6379
    host: redis
    port: 6379
    scheduler: default
    parallelism: -1

  cassandra:
    enabled: false


swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*