server:
  port: 8088
  address: 0.0.0.0

jenkins:
  enabled: true
  masters:
    - name: jenkins
      address: http://jenkins.default:80
      username: jenkins
      password: jenkins

travis:
  enabled: false
  masters:
    - name: ${services.travis.defaultMaster.name}
      baseUrl: ${services.travis.defaultMaster.baseUrl}
      address: ${services.travis.defaultMaster.address}
      githubToken: ${services.travis.defaultMaster.githubToken}

dockerRegistry:
  enabled: false

redis:
  connection: redis://redis:6379

# Igor depends on Clouddriver and Echo. These are normally configured
# in spinnaker[-local].yml (if present), otherwise, uncomment this.
# services:
  clouddriver:
    baseUrl: http://clouddriver:7002
  echo:
    baseUrl: http://echo

# spectator:
#   applicationName: ${spring.application.name}
#   webEndpoint:
#     enabled: ${services.spectator.webEndpoint.enabled:false}
#     prototypeFilter:
#       path: ${services.spectator.webEndpoint.prototypeFilter.path:}

#   stackdriver:
#     enabled: ${services.stackdriver.enabled}
#     projectName: ${services.stackdriver.projectName}
#     credentialsPath: ${services.stackdriver.credentialsPath}