bakery:
  allowMissingPackageInstallation: true
  baseUrl: http://rosco:8087
  extractBuildDetails: true
  roscoApisEnabled: true
  propagateCloudProviderType: true

rosco:
  baseUrl: http://rosco:8007
  roscoApisEnabled: true
  enabled: false
  allowMissingPackageInstallation: true

default:
  bake:
    account: docker

  securityGroups: null
  vpc:
    securityGroups: null
echo:
  baseUrl: http://echo:8089
  enabled: false
flex:
  baseUrl: http://not-a-host
front50:
  baseUrl: http://front50:8080

igor:
  enabled: true
  baseUrl: http://igor:8088
kato:
  baseUrl: http://clouddriver:7002
mort:
  baseUrl: http://clouddriver:7002
oort:
  baseUrl: http://clouddriver:7002
redis:
  enabled: true
  connection: redis://redis:6379
  scheduler: default
  parallelism: -1
server:
  port: 8083
  address: 0.0.0.0
services:
  orca:
    timezone: west
tasks:
  executionWindow:
    timezone: west
tide:
  baseUrl: http://not-a-host
  enabled: false